api/urls.py
from django.template.defaulttags import url
from django.urls import path, include
from rest_framework import routers

from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'participants', views.ParticipantViewSet)
router.register(r'contests', views.ContestViewSet)
router.register(r'attempts', views.AttemptViewSet)
router.register(r'acj', views.AttemptsCheckJobsViewSet, basename='AttemptsCheckJobs')
router.register(r'checkings_in_progress', views.CheckingInProgressViewSet, basename='AttemptsCheckJobsInProgress')
router.register(r'pending_manual_check', views.PendingManualCheckViewSet, basename='PendingManualCheck')
router.register(r'list_of_cheaters', views.ListOfCheatersViewSet, basename='ListOfCheaters')

urlpatterns = [
    path('api/', include(router.urls)),
    path('test/', views.test)
    # path('remove_groupoup/<int:group_id>/', views.test, name='test'),
]

cheaters_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cheaters_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include(('checker.urls', 'checker'), namespace='checker'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checker/urls.py
import datetime

from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from checker import views, contest_views, checking_views
from checker.forms import LoginForm

app_name = 'checker'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.main, name='main_page'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             template_name='auth/login.html',
             authentication_form=LoginForm,
             extra_context={
                 'stop_register': datetime.date.today(),
                 'year': datetime.date.today().year
             }
         ),
         name='login'
         ),
    path('group/<int:group_id>/', views.group, name='group'),
    path('group_edit/<int:group_id>/', views.edit_group, name='edit_group'),
    path('add_group/', views.add_group, name='add_group'),
    path('remove_group/<int:group_id>/', views.remove_group, name='remove_group'),
    path('contest/<int:contest_id>/', views.contest, name='contest'),
    path('pending_manual_check/', views.pending_manual_check, name='pending_manual_check'),
    path('automatic_checking/', views.automatic_checking, name='automatic_checking'),
    path('all_cheaters/', views.all_cheaters, name='all_cheaters'),
    path('my_groups/', views.my_groups, name='my_groups'),
    path('start_sync/<int:group_id>/', views.start_sync, name='start_sync'),
    path('sync_contest/<int:group_id>/<int:contest_id>/', views.sync_contest, name='sync_contest'),
    path('edit_contest_threshold/<int:group_id>/<int:contest_id>/', contest_views.edit_contest_threshold, name='edit_contest_threshold'),
    path('check_attempts/<int:attempts_check_jobs_id>/', checking_views.check_attempts, name='check_attempts'),
    path('check_my_groups/', checking_views.check_my_groups, name='check_my_groups'),
    path('check_group/<int:group_id>/', checking_views.check_group, name='check_group'),
    path('check_contest/<int:contest_id>/', checking_views.check_contest, name='check_contest'),
    path('checking_in_progress/', checking_views.checking_in_progress, name='checking_in_progress')
    # path('contests/<int:group_id>', views.list_of_contests, name='list_of_contests'),
    # path('contest/<int:contest_pk>', views.contest_result, name='contest_result')
    # path('test/', views.test_upload, name='test-upload'),
]

checker/models.py
from django.contrib.auth.models import User
from django.db import models

from checker.entities.entities import CONTEST_TYPE_CHOICES, CHECKING_STATUS_CHOICES, OUTCOME_CHOICES, AUTH_TYPE_CHOICES


# Create your models here.

# class UserType(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     auth_type = models.CharField(max_length=2, choices=AUTH_TYPE_CHOICES)
#     login_pcms = models.CharField(max_length=100, null=True, blank=True)
#     password_pcms = models.CharField(max_length=100, null=True, blank=True)
#
#     def __str__(self):
#         return self.user.username
#
#     class Meta:
#         constraints = [models.CheckConstraint(
#             name="%(app_label)s_%(class)s If you choose builtin auth, you should enter pcms login and password",
#             check=models.Q(auth_type='p') | (models.Q(auth_type='b') &
#                                              models.Q(login_pcms__isnull=False) & models.Q(
#                         password_pcms__isnull=False))
#         )]


class Group(models.Model):
    users_have_access = models.ManyToManyField(User)
    name = models.CharField(max_length=1000)
    login = models.CharField(max_length=1000)
    password = models.CharField(max_length=1000)
    api_url = models.CharField(null=True, blank=True, max_length=1000)

    class Meta:
        unique_together = ('login', 'password', 'api_url')

    def save(self, *args, **kwargs):
        from checker.tasks import delayed_parse_group
        super(Group, self).save(*args, **kwargs)
        delayed_parse_group.delay(self.pk)

    def __str__(self):
        return self.name


class Problem(models.Model):
    name = models.CharField(max_length=1000)
    pcms_id = models.CharField(max_length=1000)
    last_check_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name


class Contest(models.Model):
    users_have_access = models.ManyToManyField(User)
    group = models.ManyToManyField(Group, blank=True)
    name = models.CharField(max_length=1000)
    pcms_id = models.CharField(max_length=1000)
    contest_id = models.CharField(max_length=1000)
    scoring_model = models.CharField(max_length=50, choices=CONTEST_TYPE_CHOICES)
    last_check_time = models.DateTimeField(blank=True, null=True)
    problem = models.ManyToManyField(Problem, through='ContestProblem')
    last_page_downloaded = models.IntegerField(null=True, blank=True)
    last_attempt_id_downloaded = models.CharField(max_length=1000, null=True, blank=True)
    last_attempt_parsing_time = models.DateTimeField(auto_now_add=True)
    last_contest_problems_parsing_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContestProblem(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    alias = models.CharField(max_length=30)
    last_check_time = models.DateTimeField(null=True, blank=True)
    threshold = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f'{self.contest.name}: {self.alias}. {self.problem.name}'


class Participant(models.Model):
    pcms_id = models.CharField(max_length=1000)
    name = models.CharField(max_length=1000)
    contest = models.ManyToManyField(Contest, blank=True)

    def __str__(self):
        return self.name


class Attempt(models.Model):
    pcms_id = models.CharField(max_length=1000)
    alias = models.IntegerField(null=True)
    score = models.IntegerField()
    outcome = models.CharField(max_length=1000, choices=OUTCOME_CHOICES)
    status = models.CharField(max_length=1000, null=True, blank=True)
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    problem_contest = models.ForeignKey(ContestProblem, on_delete=models.CASCADE)
    time = models.BigIntegerField()
    language = models.CharField(max_length=1000)
    source = models.FileField(upload_to='upload/sources/')

    def __str__(self):
        return f'{self.participant.name}, {self.alias}, PRB: {self.problem_contest.problem.name}'

    class Meta:
        ordering = ['alias', 'time', 'pcms_id']
        unique_together = ('pcms_id',)


class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    contest = models.ManyToManyField(Contest, blank=True)
    problems = models.ManyToManyField(Problem, blank=True)
    participant = models.ManyToManyField(Participant, blank=True)
    groups = models.ManyToManyField(Group, blank=True)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['end_time', 'start_time']


class AttemptsCheckJobs(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, null=True)
    rmq_job_id = models.CharField(max_length=200, null=True, blank=True)
    attempt_lhs = models.ForeignKey(Attempt, on_delete=models.CASCADE, related_name='jobs_lhs')
    attempt_rhs = models.ForeignKey(Attempt, on_delete=models.CASCADE, related_name='jobs_rhs')
    script_checking_result = models.FloatField(null=True)
    status = models.CharField(max_length=100, choices=CHECKING_STATUS_CHOICES)
    checking_start_time = models.DateTimeField(null=True, blank=True)
    checking_end_time = models.DateTimeField(null=True, blank=True)
    manual_check_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('attempt_lhs', 'attempt_rhs')
        ordering = ['pk']

checker/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError

from cheaters_project.settings import main_pcms_api_url
from checker.helpers.helpers import check_login_password_exists
from checker.models import Group, ContestProblem


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Логин'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Пароль', 'class': 'form-control '
                                                                                                   'form-control-user'}))


class GroupAddForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = ['users_have_access']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control form-control-user',
                'placeholder': 'Название группы'
            }),
            'login': forms.TextInput(attrs={
                'class': 'form-control form-control-user',
                'placeholder': 'Логин от pcms'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form-control form-control-user',
                'placeholder': 'Пароль от pcms'
            }),
            'api_url': forms.TextInput(attrs={
                'class': 'form-control form-control-user',
                'placeholder': 'Необязательно: адрес pcms api, default: pcms.litsey2.ru',
            }),
        }

    def clean(self):
        login = self.cleaned_data.get('login', '')
        password = self.cleaned_data.get('password', '')
        api_url = self.cleaned_data.get('api_url', '')
        api_url = api_url if api_url else main_pcms_api_url
        continue_check = True if login and password else False
        # print(login, password, api_url)
        if check_login_password_exists(login, password, api_url) and continue_check:
            return self.cleaned_data
        raise ValidationError(f'Login password in pcms server doesn\'t exists [{login, password}]')


class ContestProblemEditForm(forms.ModelForm):
    class Meta:
        model = ContestProblem
        exclude = ['problem', 'contest', 'last_check_time', 'alias']

        widgets = {
            'threshold': forms.NumberInput(attrs={
                'class': 'form-control form-control-user',
                'placeholder': 'Погрешность'
            })
        }

    def clean_threshold(self):
        try:
            threshold = self.cleaned_data.get('threshold', '')
            print(threshold)
            threshold = float(threshold)
            if (not 0.0 <= threshold <= 1.0) or threshold == -1.0:
                raise ValidationError(f'Threshold should be between 0.0 and 1.0 or -1.0. You entered {threshold}')
            return threshold
        except UnboundLocalError:
            return threshold
        except TypeError:
            return threshold

checker/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Min, Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse

from checker.forms import GroupAddForm
from checker.helpers.helpers import get_menu_info
from checker.models import Job, Group, Contest
from checker.tasks import delayed_parse_group, delayed_parse_group_contest_attempts


# Create your views here.
@login_required()
def main(request):
    context = get_menu_info(request, 'Main')

    return render(request, 'checker/index.html', context=context)


def login_auth(request):
    pass


@login_required()
def group(request, group_id: int):
    group = Group.objects.get(pk=group_id)
    context = get_menu_info(request, group.name)
    contests = Contest.objects.filter(group__in=[group])
    context['contests'] = contests
    context['group'] = group
    return render(request, 'checker/group.html', context=context)


@login_required()
def add_group(request):
    if request.method == 'POST':
        form = GroupAddForm(request.POST)
        if form.is_valid():
            grp = form.save()
            grp.users_have_access.add(request.user)
        else:
            print('Form is not valid', form)

    return HttpResponseRedirect(reverse('checker:my_groups'))


@login_required()
def edit_group(request, group_id: int):
    context = get_menu_info(request, 'Edit_group')
    return render(request, 'checker/index.html', context=context)


@login_required()
def contest(request, contest_id: int):
    context = get_menu_info(request, 'Contest')
    return render(request, 'checker/groups.html', context=context)


@login_required()
def pending_manual_check(request):
    context = get_menu_info(request, 'Pending manual check')
    return render(request, 'checker/pending_manual_check.html', context=context)


@login_required()
def automatic_checking(request):
    context = get_menu_info(request, 'Automatic checking')
    return render(request, 'checker/index.html', context=context)


@login_required()
def all_cheaters(request):
    context = get_menu_info(request, "All cheaters")
    return render(request, 'checker/list_of_cheaters.html', context=context)


@login_required()
def remove_group(request, group_id):
    try:
        gr = Group.objects.get(pk=group_id)
        gr.delete()
    except Group.DoesNotExist:
        print(f'Group with id {group_id} doesnt exists.')
    return HttpResponseRedirect(reverse('checker:my_groups'))


@login_required()
def my_groups(request):
    context = get_menu_info(request, 'Мои группы')
    addGroupForm = GroupAddForm()
    myGroups = Group.objects. \
        filter(users_have_access__in=[request.user]). \
        values('pk', 'name', 'login', 'password', 'api_url').annotate(
            last_contest_problems_parsing_time=Min('contest__last_contest_problems_parsing_time'),
            last_attempt_parsing_time=Min('contest__last_attempt_parsing_time'), num_of_contests=Count('contest__name'),
            last_check_time=Min('contest__last_check_time'))
    context['my_groups'] = myGroups
    context['addGroupForm'] = addGroupForm
    return render(request, 'checker/groups.html', context)


@login_required()
def start_sync(request, group_id):
    # grp = Group.objects.get(pk=group_id)
    delayed_parse_group.delay(group_id)
    return HttpResponseRedirect(reverse('checker:group', kwargs={'group_id': group_id}))


@login_required()
def sync_contest(request, group_id, contest_id):
    delayed_parse_group_contest_attempts.delay(group_id, contest_id)
    return HttpResponseRedirect(reverse('checker:group', kwargs={'group_id': group_id}))

checker/templates/checker/contest_problem.html
{% extends 'checker/base.html' %}
{% load form_extras %}
{% block nav_items_messages %}
{% load static %}
{% endblock %}
{% block navbar %}

{% endblock %}

{% block content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        {#                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>#}
        {#                    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.#}
        {#                        For more information about DataTables, please visit the <a target="_blank"#}
        {#                            href="https://datatables.net">official DataTables documentation</a>.</p>#}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ page_title }}</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <form class="" id="msform" method="post"
                          action="{% url 'checker:edit_contest_threshold' group.pk contest.pk %}">
                    {% csrf_token %}
                                        {{ formset.management_form }}


                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Alias</th>
                                <th>Problem</th>
                                <th>Threshold</th>
                                <th>Last check time</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Alias</th>
                                <th>Problem</th>
                                <th>Threshold</th>
                                <th>Last check time</th>

                            </tr>
                            </tfoot>
                            <tbody>
                            {% for cproblem in contest_problems %}

                                <tr class="text-center">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ cproblem.alias }}</td>
                                    <td>{{ cproblem.problem.name }}</td>
                                    <td>{{ formset|get_at_index_threshold:forloop.counter0 }}</td>
                                    <td>{{ cproblem.last_check_time }}</td>

                                    {#                                <td>#}
                                    {#                                    <a href="{% url 'checker:start_sync' contest.pk %}"#}
                                    {#                                       class="btn btn-info btn-circle" >#}
                                    {#                                        <i class="fas fa-user-check"></i>#}
                                    {#                                    </a>#}
                                    {#                                    <a href="{% url 'checker:sync_contest' group.pk contest.pk %}"#}
                                    {#                                       class="btn btn-success btn-circle" >#}
                                    {#                                        <i class="fas fa-sync"></i>#}
                                    {#                                    </a>#}
                                    {#                                    <a href="{% url 'checker:edit_contest_threshold' group.pk contest.pk %}"#}
                                    {#                                       class="btn btn-warning btn-circle" >#}
                                    {#                                        <i class="fas fa-pen"></i>#}
                                    {#                                    </a>#}
                                    {#                                </td>#}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                            {% for form in formset %}
{#                                {{form.hidden_fields}}#}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}

                                {% endfor %}

                            {% endfor %}
                        <a href="{% url 'checker:group' group.id %}" class="btn btn-secondary">Назад к контестам</a>
                        <input type="submit" name="Submit" class="btn btn-primary"
                               value="Сохранить"/>
                    </form>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

{% block right_upper_button %}

{% endblock %}

{% block custom_footer_scripts %}
<script src="{% static 'checker/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

checker/templates/checker/group.html
{% extends 'checker/base.html' %}
{% load static %}
{% block navbar %}
{% endblock %}
{% block title %}
    Группа {{ page_title }}
{% endblock %}
{% block right_upper_button %}
        <a href="{% url 'checker:check_group' group.pk %}?from={{ request.path }}"
       class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i
            class="fas fa-plus fa-sm text-white-50"></i> Проверить все контесты группы</a>
{% endblock %}
{% block nav_items_messages %}
{% endblock %}
{% block content %}

    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        {#                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>#}
        {#                    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.#}
        {#                        For more information about DataTables, please visit the <a target="_blank"#}
        {#                            href="https://datatables.net">official DataTables documentation</a>.</p>#}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ page_title }}</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Название контеста</th>
                            <th>Количество задач</th>
                            <th>Последнее обновление посылок</th>
                            <th>Последнее обновление задач</th>
                            <th>Последняя проверка</th>
                            <th>Ручная проверка</th>
                            <th>Списываний</th>
                            <th>Действия с контестом</th>

                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Название контеста</th>
                            <th>Количество задач</th>
                            <th>Последнее обновление посылок</th>
                            <th>Последнее обновление задач</th>
                            <th>Последняя проверка</th>
                            <th>Ручная проверка</th>
                            <th>Списываний</th>
                            <th>Действия с контестом</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for contest in contests %}

                            <tr class="text-center">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ contest.name }}</td>
                                <td>{{ contest.contestproblem_set.count }}</td>
                                <td>{{ contest.last_attempt_parsing_time }}</td>
                                <td>{{ contest.last_contest_problems_parsing_time }}</td>
                                <td>{{ contest.last_check_time }}</td>
                                <td>Ручная проверка</td>
                                <td>Списываний</td>
                                <td>
                                    <a href="{% url 'checker:check_contest' contest.pk %}?from={{ request.path }}"
                                       class="btn btn-info btn-circle" >
                                        <i class="fas fa-user-check"></i>
                                    </a>
                                    <a href="{% url 'checker:sync_contest' group.pk contest.pk %}"
                                       class="btn btn-success btn-circle" >
                                        <i class="fas fa-sync"></i>
                                    </a>
                                    <a href="{% url 'checker:edit_contest_threshold' group.pk contest.pk %}"
                                       class="btn btn-warning btn-circle" >
                                        <i class="fas fa-pen"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
{##}
{#    {% include 'checker/addGroupModal.html' %}#}
{#    {% include 'checker/DeleteGroupModal.html' %}#}
    <!-- /.container-fluid -->


{% endblock %}
{% block custom_footer_scripts %}
<script src="{% static 'checker/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

checker/templates/checker/groups.html
{% extends 'checker/base.html' %}
{% load static %}
{% block navbar %}
{% endblock %}
{% block right_upper_button %}
    <a href="#" data-toggle="modal" data-target="#addGroupModal"
       class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-plus fa-sm text-white-50"></i> Добавить группу</a>
        <a href="{% url 'checker:check_my_groups' %}"
       class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i
            class="fas fa-plus fa-sm text-white-50"></i> Проверить всё</a>
{% endblock %}
{% block nav_items_messages %}
{% endblock %}
{% block content %}

    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        {#                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>#}
        {#                    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.#}
        {#                        For more information about DataTables, please visit the <a target="_blank"#}
        {#                            href="https://datatables.net">official DataTables documentation</a>.</p>#}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ page_title }}</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название группы</th>
                            <th>Количество контестов</th>
                            <th>Последнее обновление посылок</th>
                            <th>Последняя обновление задач</th>
                            <th>Последняя проверка</th>
                            <th>Действия с группой</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Название группы</th>
                            <th>Количество контестов</th>
                            <th>Последнее обновление посылок</th>
                            <th>Последняя обновление задач</th>
                            <th>Последняя проверка</th>
                            <th>Действия с группой</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for group in my_groups %}

                            <tr class="text-center">
                                <td><a href="{% url 'checker:group' group.pk %}">{{ group.name }}</a></td>
                                <td>{{ group.num_of_contests }}</td>
                                <td>{{ group.last_attempt_parsing_time }}</td>
                                <td>{{ group.last_contest_problems_parsing_time }}</td>
                                <td>{{ group.last_check_time }}</td>
                                <td>
                                    <a href="{% url 'checker:check_group' group.pk %}?from={{ request.path }}"
                                       class="btn btn-info btn-circle" >
                                        <i class="fas fa-user-check"></i>
                                    </a>
                                    <a href="{% url 'checker:start_sync' group.pk %}"
                                       class="btn btn-success btn-circle" >
                                        <i class="fas fa-sync"></i>
                                    </a>
                                    <a href="#" data-toggle="modal" data-target="#deleteGroupModal"
                                       class="btn btn-warning btn-circle">
                                    <i class="fas fa-pen"></i></a>
                                    <a href="{% url 'checker:remove_group' group.pk %}"
                                       class="btn btn-danger btn-circle">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    {% include 'checker/addGroupModal.html' %}
{#    {% include 'checker/DeleteGroupModal.html' %}#}
    <!-- /.container-fluid -->


{% endblock %}
{% block custom_footer_scripts %}
<script src="{% static 'checker/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

checker/templates/checker/index.html
{% extends 'checker/base.html' %}
{% load static %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block navbar %}

{% endblock %}

{% block nav_items_messages %}

{% endblock %}